/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"

// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *biquad_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _biquad {
    t_object x_obj;
    t_float x_f;
    t_inlet * x_inlet_dsp_0;
    t_inlet * x_inlet_dsp_1;
    t_inlet * x_inlet_dsp_2;
    t_inlet * x_inlet_dsp_3;
    t_inlet * x_inlet_dsp_4;
    float  x_xnm1;
    float  x_xnm2;
    float  x_ynm1;
    float  x_ynm2;
    t_outlet * x_outlet_dsp_0;
    
} t_biquad;

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * biquad_new(void);// Constructor
void biquad_destroy(t_biquad *x); //Destructor
void biquad_clear(t_biquad *x); // Message function
static t_int * biquad_perform(t_int *w); //Perform function
static void biquad_dsp(t_biquad *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// biquad_clear
// ---------------------------------------------------
void biquad_clear(t_biquad *x){
   x->x_xnm1 = x->x_xnm2 = x->x_ynm1 = x->x_ynm2 = 0.;
}

// ---------------------------------------------------
// biquad_stoke
// ---------------------------------------------------
void biquad_stoke(t_biquad *x,
    t_floatarg f1, t_floatarg f2, t_floatarg f3, t_floatarg f4)
{
    x->x_xnm1 = f1;
    x->x_xnm2 = f2;
    x->x_ynm1 = f3;
    x->x_ynm2 = f4;
}

// ---------------------------------------------------
// biquad_smooth
// ---------------------------------------------------
void biquad_smooth(t_biquad *x, t_floatarg f){
}

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * biquad_perform(t_int *w){
    t_biquad *x = (t_biquad *)(w[1]);
    int n = (int)(w[2]);
    t_float *in = (t_float *)(w[3]);
    t_float *coef_a0 = (t_float *)(w[4]);
    t_float *coef_a1 = (t_float *)(w[5]);
    t_float *coef_a2 = (t_float *)(w[6]);
    t_float *coef_b1 = (t_float *)(w[7]);
    t_float *coef_b2 = (t_float *)(w[8]);
    t_float *out = (t_float *)(w[9]);
    float xnm1 = x->x_xnm1;
    float xnm2 = x->x_xnm2;
    float ynm1 = x->x_ynm1;
    float ynm2 = x->x_ynm2;
    while (n--)
        {
        float yn, xn = *in++;
        float a0 = *coef_a0++;
        float a1 = *coef_a1++;
        float a2 = *coef_a2++;
        float b1 = *coef_b1++;
        float b2 = *coef_b2++;
        *out++ = yn = a0 * xn + a1 * xnm1 + a2 * xnm2 -b1 * ynm1 -b2 * ynm2;
        xnm2 = xnm1;
        xnm1 = xn;
        ynm2 = ynm1;
        ynm1 = yn;
        }
    x->x_xnm1 = xnm1;
    x->x_xnm2 = xnm2;
    x->x_ynm1 = ynm1;
    x->x_ynm2 = ynm2;
    return (w + 10);
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void biquad_dsp(t_biquad *x, t_signal **sp){
    dsp_add(biquad_perform, 9, x, sp[0]->s_n, sp[0]->s_vec, sp[1]->s_vec,
            sp[2]->s_vec, sp[3]->s_vec, sp[4]->s_vec, sp[5]->s_vec, sp[6]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * biquad_new(void){
    t_biquad *x = (t_biquad *) pd_new(biquad_class);
    x->x_inlet_dsp_0 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
    x->x_inlet_dsp_1 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
    x->x_inlet_dsp_2 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
    x->x_inlet_dsp_3 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
    x->x_inlet_dsp_4 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
    x->x_xnm1 = 0;
    x->x_xnm2 = 0;
    x->x_ynm1 = 0;
    x->x_ynm2 = 0;
    x->x_outlet_dsp_0 = outlet_new(&x->x_obj, &s_signal);
    return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void biquad_destroy(t_biquad *x)
{
    inlet_free(x->x_inlet_dsp_0);
    inlet_free(x->x_inlet_dsp_1);
    inlet_free(x->x_inlet_dsp_2);
    inlet_free(x->x_inlet_dsp_3);
    inlet_free(x->x_inlet_dsp_4);
    
    outlet_free(x->x_outlet_dsp_0);
}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void biquad_tilde_setup(void)
{
    biquad_class = class_new(gensym("cyclone/biquad~"),
                             (t_newmethod) biquad_new, // Constructor
                             (t_method) biquad_destroy, // Destructor
                             sizeof (t_biquad),
                             CLASS_DEFAULT, // Tipo de classe
                             0);//Must always ends with a zero
    CLASS_MAINSIGNALIN(biquad_class, t_biquad, x_f);
    class_addmethod(biquad_class, (t_method) biquad_clear, gensym("clear"), 0);
    class_addmethod(biquad_class, (t_method) biquad_stoke, gensym("stoke"),
                    A_DEFFLOAT, A_DEFFLOAT, A_DEFFLOAT, A_DEFFLOAT, 0);
    class_addmethod(biquad_class, (t_method) biquad_smooth, gensym("smooth"), A_DEFFLOAT, 0);
    class_addmethod(biquad_class, (t_method) biquad_dsp, gensym("dsp"), 0);
}