EXTENSION="pd_linux"
rm Append.$EXTENSION Bucket.$EXTENSION Clip.$EXTENSION Decode.$EXTENSION Histo.$EXTENSION MouseState.$EXTENSION Peak.$EXTENSION Table.$EXTENSION TogEdge.$EXTENSION Trough.$EXTENSION Uzi.$EXTENSION Clip~.$EXTENSION Line~.$EXTENSION Scope~.$EXTENSION Snapshot~.$EXTENSION
