// For information on usage and redistribution, and for a DISCLAIMER OF ALL
// WARRANTIES, see the file, \"LICENSE.txt,\" in this distribution.
// Copyright (c) 1997-2009 Miller Puckette.

sys_gui("package provide dialog_comment 0.1\n");
sys_gui("namespace eval ::dialog_comment:: {   \n");
sys_gui("namespace export pdtk_comment_dialog\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_clip_ents {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
//dimensions
sys_gui("set var_comment_wdt [concat comment_wdt_$vid]\n");
sys_gui("global $var_comment_wdt\n");
sys_gui("set var_comment_hgt [concat comment_hgt_$vid]\n");
sys_gui("global $var_comment_hgt\n");
sys_gui("set var_comment_wdt_min [concat comment_wdt_min_$vid]\n");
sys_gui("global $var_comment_wdt_min\n");
sys_gui("set var_comment_hgt_min [concat comment_hgt_min_$vid]\n");
sys_gui("global $var_comment_hgt_min\n");
//buffer
sys_gui("set var_comment_cal [concat comment_cal_$vid]\n");
sys_gui("global $var_comment_cal\n");
sys_gui("set var_comment_bfs [concat comment_bfs_$vid]\n");
sys_gui("global $var_comment_bfs\n");
sys_gui("set var_comment_cal_min [concat comment_cal_min_$vid]\n");
sys_gui("global $var_comment_cal_min\n");
sys_gui("set var_comment_cal_max [concat comment_cal_max_$vid]\n");
sys_gui("global $var_comment_cal_max\n");
sys_gui("set var_comment_bfs_min [concat comment_bfs_min_$vid]\n");
sys_gui("global $var_comment_bfs_min\n");
sys_gui("set var_comment_bfs_max [concat comment_bfs_max_$vid]\n");
sys_gui("global $var_comment_bfs_max\n");
//delay
sys_gui("set var_comment_del [concat comment_del_$vid]\n");
sys_gui("global $var_comment_del\n");
sys_gui("set var_comment_del_min [concat comment_del_min_$vid]\n");
sys_gui("global $var_comment_del_min\n");
//dimensions
sys_gui("if { [eval concat $$var_comment_wdt] < [eval concat $$var_comment_wdt_min] } {\n");
sys_gui("set $var_comment_wdt [eval concat $$var_comment_wdt_min] \n");
sys_gui("$mytoplevel.dim.fr.w_ent configure -textvariable $var_comment_wdt\n");
sys_gui("}\n");
sys_gui("if { [eval concat $$var_comment_hgt] < [eval concat $$var_comment_hgt_min] } {\n");
sys_gui("set $var_comment_hgt [eval concat $$var_comment_hgt_min] \n");
sys_gui("$mytoplevel.dim.fr.h_ent configure -textvariable $var_comment_hgt\n");
sys_gui("}\n");
//buffer
sys_gui("if { [eval concat $$var_comment_cal] < [eval concat $$var_comment_cal_min] } {\n");
sys_gui("set $var_comment_cal [eval concat $$var_comment_cal_min] \n");
sys_gui("$mytoplevel.buf.fr.cal_ent configure -textvariable $var_comment_cal\n");
sys_gui("}\n");
sys_gui("if { [eval concat $$var_comment_cal] > [eval concat $$var_comment_cal_max] } {\n");
sys_gui("set $var_comment_cal [eval concat $$var_comment_cal_max] \n");
sys_gui("$mytoplevel.buf.fr.cal_ent configure -textvariable $var_comment_cal\n");
sys_gui("}\n");
sys_gui("if { [eval concat $$var_comment_bfs] < [eval concat $$var_comment_bfs_min] } {\n");
sys_gui("set $var_comment_bfs [eval concat $$var_comment_bfs_min] \n");
sys_gui("$mytoplevel.buf.fr.bfs_ent configure -textvariable $var_comment_bfs\n");
sys_gui("}\n");
sys_gui("if { [eval concat $$var_comment_bfs] > [eval concat $$var_comment_bfs_max] } {\n");
sys_gui("set $var_comment_bfs [eval concat $$var_comment_bfs_max] \n");
sys_gui("$mytoplevel.buf.fr.bfs_ent configure -textvariable $var_comment_bfs\n");
sys_gui("}\n");
//delay
sys_gui("if { [eval concat $$var_comment_del] < [eval concat $$var_comment_del_min] } {\n");
sys_gui("set $var_comment_del [eval concat $$var_comment_del_min] \n");
sys_gui("$mytoplevel.misc.fr.del_ent configure -textvariable $var_comment_del\n");
sys_gui("}\n");
sys_gui("}    \n");
sys_gui("proc ::dialog_comment::comment_check_range {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_min_rng [concat comment_min_rng_$vid]\n");
sys_gui("global $var_comment_min_rng\n");
sys_gui("set var_comment_max_rng [concat comment_max_rng_$vid]\n");
sys_gui("global $var_comment_max_rng\n");
sys_gui("if { [eval concat $$var_comment_min_rng] > [eval concat $$var_comment_max_rng] } {\n");
sys_gui("set temp [eval concat $$var_comment_min_rng]\n");
sys_gui("set $var_comment_min_rng [eval concat $$var_comment_max_rng]\n");
sys_gui("set $var_comment_max_rng [eval concat $temp]\n");
sys_gui("$mytoplevel.rng.fr.min_ent configure -textvariable $var_comment_min_rng\n");
sys_gui("$mytoplevel.rng.fr.max_ent configure -textvariable $var_comment_max_rng\n");
sys_gui("}\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_empty_ents {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_wdt [concat comment_wdt_$vid]\n");
sys_gui("global $var_comment_wdt\n");
sys_gui("set var_comment_hgt [concat comment_hgt_$vid]\n");
sys_gui("global $var_comment_hgt\n");
sys_gui("set var_comment_cal [concat comment_cal_$vid]\n");
sys_gui("global $var_comment_cal\n");
sys_gui("set var_comment_bfs [concat comment_bfs_$vid]\n");
sys_gui("global $var_comment_bfs\n");
sys_gui("set var_comment_min_rng [concat comment_min_rng_$vid]\n");
sys_gui("global $var_comment_min_rng\n");
sys_gui("set var_comment_max_rng [concat comment_max_rng_$vid]\n");
sys_gui("global $var_comment_max_rng\n");
sys_gui("set var_comment_del [concat comment_del_$vid]\n");
sys_gui("global $var_comment_del\n");
sys_gui("set var_comment_tlv [concat comment_tlv_$vid]\n");
sys_gui("global $var_comment_tlv\n");
sys_gui("set var_comment_drs [concat comment_drs_$vid]\n");
sys_gui("set var_comment_wdt_init [concat comment_wdt_init_$vid]\n");
sys_gui("global $var_comment_wdt_init\n");
sys_gui("set var_comment_hgt_init [concat comment_hgt_init_$vid]\n");
sys_gui("global $var_comment_hgt_init\n");
sys_gui("set var_comment_cal_init [concat comment_cal_init_$vid]\n");
sys_gui("global $var_comment_cal_init\n");
sys_gui("set var_comment_bfs_init [concat comment_bfs_init_$vid]\n");
sys_gui("global $var_comment_bfs_init\n");
sys_gui("set var_comment_min_rng_init [concat comment_min_rng_init_$vid]\n");
sys_gui("global $var_comment_min_rng_init\n");
sys_gui("set var_comment_max_rng_init [concat comment_max_rng_init_$vid]\n");
sys_gui("global $var_comment_max_rng_init\n");
sys_gui("set var_comment_del_init [concat comment_del_init_$vid]\n");
sys_gui("global $var_comment_del_init\n");
sys_gui("set var_comment_tlv_init [concat comment_tlv_init_$vid]\n");
sys_gui("global $var_comment_tlv_init\n");
sys_gui("if {[eval concat $$var_comment_wdt] eq \"\"} {set $var_comment_wdt [eval concat $$var_comment_wdt_init]}\n");
sys_gui("if {[eval concat $$var_comment_hgt] eq \"\"} {set $var_comment_hgt [eval concat $$var_comment_hgt_init]}\n");
sys_gui("if {[eval concat $$var_comment_cal] eq \"\"} {set $var_comment_cal [eval concat $$var_comment_cal_init]}\n");
sys_gui("if {[eval concat $$var_comment_bfs] eq \"\"} {set $var_comment_bfs [eval concat $$var_comment_bfs_init]}\n");
sys_gui("if {[eval concat $$var_comment_min_rng] eq \"\"} {set $var_comment_min_rng [eval concat $$var_comment_min_rng_init]}\n");
sys_gui("if {[eval concat $$var_comment_max_rng] eq \"\"} {set $var_comment_max_rng [eval concat $$var_comment_max_rng_init]}\n");
sys_gui("if {[eval concat $$var_comment_del] eq \"\"} {set $var_comment_del [eval concat $$var_comment_del_init]}\n");
sys_gui("if {[eval concat $$var_comment_tlv] eq \"\"} {set $var_comment_tlv [eval concat $$var_comment_tlv_init]}\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_set_col_example {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_bcol [concat comment_bcol_$vid]\n");
sys_gui("global $var_comment_bcol\n");
sys_gui("set var_comment_gcol [concat comment_gcol_$vid]\n");
sys_gui("global $var_comment_gcol\n");
sys_gui("set var_comment_fcol [concat comment_fcol_$vid]\n");
sys_gui("global $var_comment_fcol\n");
sys_gui("$mytoplevel.colors.commentvis.cv itemconfigure \"bg\" -fill [eval concat $$var_comment_bcol]\n");
sys_gui("$mytoplevel.colors.commentvis.cv itemconfigure \"gr\" -fill [eval concat $$var_comment_gcol]\n");
sys_gui("$mytoplevel.colors.commentvis.cv itemconfigure \"fg\" -fill [eval concat $$var_comment_fcol]\n");
// for OSX live updates
sys_gui("if {$::windowingsystem eq \"aqua\"} {\n");
sys_gui("::dialog_comment::apply_and_rebind_return $mytoplevel\n");
sys_gui("}\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_preset_col {mytoplevel presetcol} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_f2_g1_b0 [concat comment_f2_g1_b0_$vid]\n");
sys_gui("global $var_comment_f2_g1_b0\n");
sys_gui("set var_comment_bcol [concat comment_bcol_$vid]\n");
sys_gui("global $var_comment_bcol\n");
sys_gui("set var_comment_gcol [concat comment_gcol_$vid]\n");
sys_gui("global $var_comment_gcol\n");
sys_gui("set var_comment_fcol [concat comment_fcol_$vid]\n");
sys_gui("global $var_comment_fcol\n");
sys_gui("if { [eval concat $$var_comment_f2_g1_b0] == 0 } { set $var_comment_bcol $presetcol }\n");
sys_gui("if { [eval concat $$var_comment_f2_g1_b0] == 1 } { set $var_comment_gcol $presetcol }\n");
sys_gui("if { [eval concat $$var_comment_f2_g1_b0] == 2 } { set $var_comment_fcol $presetcol }\n");
sys_gui("::dialog_comment::comment_set_col_example $mytoplevel\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_choose_col_bkgrfg {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_f2_g1_b0 [concat comment_f2_g1_b0_$vid]\n");
sys_gui("global $var_comment_f2_g1_b0\n");
sys_gui("set var_comment_bcol [concat comment_bcol_$vid]\n");
sys_gui("global $var_comment_bcol\n");
sys_gui("set var_comment_gcol [concat comment_gcol_$vid]\n");
sys_gui("global $var_comment_gcol\n");
sys_gui("set var_comment_fcol [concat comment_fcol_$vid]\n");
sys_gui("global $var_comment_fcol\n");
sys_gui("if {[eval concat $$var_comment_f2_g1_b0] == 0} {\n");
sys_gui("set $var_comment_bcol [eval concat $$var_comment_bcol]\n");
sys_gui("set helpstring [tk_chooseColor -title [_ \"Background color\"] -initialcolor [eval concat $$var_comment_bcol]]\n");
sys_gui("if { $helpstring ne \"\" } {\n");
sys_gui("set $var_comment_bcol $helpstring }\n");
sys_gui("}\n");
sys_gui("if {[eval concat $$var_comment_f2_g1_b0] == 1} {\n");
sys_gui("set $var_comment_gcol [eval concat $$var_comment_gcol]\n");
sys_gui("set helpstring [tk_chooseColor -title [_ \"Grid color\"] -initialcolor [eval concat $$var_comment_gcol]]\n");
sys_gui("if { $helpstring ne \"\" } {\n");
sys_gui("set $var_comment_gcol $helpstring }\n");
sys_gui("}\n");
sys_gui("if {[eval concat $$var_comment_f2_g1_b0] == 2} {\n");
sys_gui("set $var_comment_fcol [eval concat $$var_comment_fcol]\n");
sys_gui("set helpstring [tk_chooseColor -title [_ \"Phosphor color\"] -initialcolor [eval concat $$var_comment_fcol]]\n");
sys_gui("if { $helpstring ne \"\" } {\n");
sys_gui("set $var_comment_fcol $helpstring }\n");
sys_gui("}\n");
sys_gui("::dialog_comment::comment_set_col_example $mytoplevel\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::comment_trigger_mode {mytoplevel tmd} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_tmd [concat comment_tmd_$vid]\n");
sys_gui("global $var_comment_tmd\n");
sys_gui("set var_comment_tmd0 [concat comment_tmd0_$vid]\n");
sys_gui("global $var_comment_tmd0\n");
sys_gui("set var_comment_tmd1 [concat comment_tmd1_$vid]\n");
sys_gui("global $var_comment_tmd1\n");
sys_gui("set var_comment_tmd2 [concat comment_tmd2_$vid]\n");
sys_gui("global $var_comment_tmd2\n");
sys_gui("if {$tmd == 0} {\n");
sys_gui("set $var_comment_tmd 0\n");
sys_gui("$mytoplevel.trg.tmd.trb configure -text [eval concat $$var_comment_tmd0]\n");
sys_gui("} elseif {$tmd == 1} {\n");
sys_gui("set $var_comment_tmd 1\n");
sys_gui("$mytoplevel.trg.tmd.trb configure -text [eval concat $$var_comment_tmd1]\n");
sys_gui("} else {\n");
sys_gui("set $var_comment_tmd 2\n");
sys_gui("$mytoplevel.trg.tmd.trb configure -text [eval concat $$var_comment_tmd2]\n");
sys_gui("}\n");
// for OSX live updates
sys_gui("if {$::windowingsystem eq \"aqua\"} {\n");
sys_gui("::dialog_comment::apply_and_rebind_return $mytoplevel\n");
sys_gui("}\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::apply {mytoplevel} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_wdt [concat comment_wdt_$vid]\n");
sys_gui("global $var_comment_wdt\n");
sys_gui("set var_comment_hgt [concat comment_hgt_$vid]\n");
sys_gui("global $var_comment_hgt\n");
sys_gui("set var_comment_cal [concat comment_cal_$vid]\n");
sys_gui("global $var_comment_cal\n");
sys_gui("set var_comment_bfs [concat comment_bfs_$vid]\n");
sys_gui("global $var_comment_bfs\n");
sys_gui("set var_comment_min_rng [concat comment_min_rng_$vid]\n");
sys_gui("global $var_comment_min_rng\n");
sys_gui("set var_comment_max_rng [concat comment_max_rng_$vid]\n");
sys_gui("global $var_comment_max_rng\n");
sys_gui("set var_comment_del [concat comment_del_$vid]\n");
sys_gui("global $var_comment_del\n");
sys_gui("set var_comment_tmd [concat comment_tmd_$vid]\n");
sys_gui("global $var_comment_tmd\n");
sys_gui("set var_comment_tlv [concat comment_tlv_$vid]\n");
sys_gui("global $var_comment_tlv\n");
sys_gui("set var_comment_drs [concat comment_drs_$vid]\n");
sys_gui("global $var_comment_drs\n");
sys_gui("set var_comment_bcol [concat comment_bcol_$vid]\n");
sys_gui("global $var_comment_bcol\n");
sys_gui("set var_comment_gcol [concat comment_gcol_$vid]\n");
sys_gui("global $var_comment_gcol\n");
sys_gui("set var_comment_fcol [concat comment_fcol_$vid]\n");
sys_gui("global $var_comment_fcol\n");
sys_gui("::dialog_comment::comment_empty_ents $mytoplevel\n");
sys_gui("::dialog_comment::comment_clip_ents $mytoplevel\n");
sys_gui("::dialog_comment::comment_check_range $mytoplevel\n");
sys_gui("pdsend [concat $mytoplevel dialog \\\n");
sys_gui("[eval concat $$var_comment_wdt] \\\n");
sys_gui("[eval concat $$var_comment_hgt] \\\n");
sys_gui("[eval concat $$var_comment_cal] \\\n");
sys_gui("[eval concat $$var_comment_bfs] \\\n");
sys_gui("[eval concat $$var_comment_min_rng] \\\n");
sys_gui("[eval concat $$var_comment_max_rng] \\\n");
sys_gui("[eval concat $$var_comment_del] \\\n");
sys_gui("[eval concat $$var_comment_drs] \\\n");
sys_gui("[eval concat $$var_comment_tmd] \\\n");
sys_gui("[eval concat $$var_comment_tlv] \\\n");
sys_gui("[eval concat $$var_comment_bcol] \\\n");
sys_gui("[eval concat $$var_comment_gcol] \\\n");
sys_gui("[eval concat $$var_comment_fcol]]\n");
sys_gui("}	\n");
// 	foreach ent {$var_comment_wdt $var_comment_hgt $var_comment_cal $var_comment_bfs
// make sure the offset boxes have a value
//     if {[eval concat $$var_iemgui_gn_dx] eq \"\"} {set $var_iemgui_gn_dx 0}
//     if {[eval concat $$var_iemgui_gn_dy] eq \"\"} {set $var_iemgui_gn_dy 0}
//     pdsend [concat $mytoplevel dialog \\
//             [eval concat $$var_iemgui_wdt] \\
//             [eval concat $$var_iemgui_hgt] \\
//             [eval concat $$var_iemgui_min_rng] \\
//             [eval concat $$var_iemgui_max_rng] \\
//             [eval concat $$var_iemgui_bcol] \\
//             [eval concat $$var_iemgui_fcol] \\
//             [eval concat $$var_iemgui_lcol] \\
//             [eval concat $$var_iemgui_steady]]
sys_gui("proc ::dialog_comment::cancel {mytoplevel} {\n");
sys_gui("pdsend \"$mytoplevel cancel\"\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::ok {mytoplevel} {\n");
sys_gui("::dialog_comment::apply $mytoplevel\n");
sys_gui("::dialog_comment::cancel $mytoplevel\n");
sys_gui("}\n");
sys_gui("proc ::dialog_comment::pdtk_comment_dialog {mytoplevel \\\n");
sys_gui("dim_header wdt wdt_label hgt hgt_label \\\n");
sys_gui("buf_header cal cal_label bfs bfs_label \\\n");
sys_gui("rng_header min_rng min_rng_label max_rng max_rng_label \\\n");
sys_gui("del_header del del_label drs_header drs drs_label\\\n");
sys_gui("trg_header tmd tmd_label tlv tlv_label \\\n");
sys_gui("dim_mins wdt_min hgt_min \\\n");
sys_gui("cal_min_max cal_min cal_max bfs_min_max bfs_min bfs_max \\\n");
sys_gui("del_mins del_min \\\n");
sys_gui("bcol gcol fcol} {\n");
sys_gui("set vid [string trimleft $mytoplevel .]\n");
sys_gui("set var_comment_wdt [concat comment_wdt_$vid]\n");
sys_gui("global $var_comment_wdt\n");
sys_gui("set var_comment_hgt [concat comment_hgt_$vid]\n");
sys_gui("global $var_comment_hgt\n");
sys_gui("set var_comment_cal [concat comment_cal_$vid]\n");
sys_gui("global $var_comment_cal\n");
sys_gui("set var_comment_bfs [concat comment_bfs_$vid]\n");
sys_gui("global $var_comment_bfs\n");
sys_gui("set var_comment_min_rng [concat comment_min_rng_$vid]\n");
sys_gui("global $var_comment_min_rng\n");
sys_gui("set var_comment_max_rng [concat comment_max_rng_$vid]\n");
sys_gui("global $var_comment_max_rng\n");
sys_gui("set var_comment_del [concat comment_del_$vid]\n");
sys_gui("global $var_comment_del\n");
sys_gui("set var_comment_tmd [concat comment_tmd_$vid]\n");
sys_gui("global $var_comment_tmd\n");
sys_gui("set var_comment_tmd0 [concat comment_tmd0_$vid]\n");
sys_gui("global $var_comment_tmd0\n");
sys_gui("set var_comment_tmd1 [concat comment_tmd1_$vid]\n");
sys_gui("global $var_comment_tmd1\n");
sys_gui("set var_comment_tmd2 [concat comment_tmd2_$vid]\n");
sys_gui("global $var_comment_tmd2\n");
sys_gui("set var_comment_tlv [concat comment_tlv_$vid]\n");
sys_gui("global $var_comment_tlv\n");
sys_gui("set var_comment_drs [concat comment_drs_$vid]\n");
sys_gui("global $var_comment_drs\n");
sys_gui("set var_comment_f2_g1_b0 [concat comment_f2_g1_b0_$vid]\n");
sys_gui("global $var_comment_f2_g1_b0\n");
sys_gui("set var_comment_bcol [concat comment_bcol_$vid]\n");
sys_gui("global $var_comment_bcol\n");
sys_gui("set var_comment_gcol [concat comment_gcol_$vid]\n");
sys_gui("global $var_comment_gcol\n");
sys_gui("set var_comment_fcol [concat comment_fcol_$vid]\n");
sys_gui("global $var_comment_fcol\n");
sys_gui("set var_comment_wdt_min [concat comment_wdt_min_$vid]\n");
sys_gui("global $var_comment_wdt_min\n");
sys_gui("set var_comment_hgt_min [concat comment_hgt_min_$vid]\n");
sys_gui("global $var_comment_hgt_min\n");
sys_gui("set var_comment_cal_min [concat comment_cal_min_$vid]\n");
sys_gui("global $var_comment_cal_min\n");
sys_gui("set var_comment_cal_max [concat comment_cal_max_$vid]\n");
sys_gui("global $var_comment_cal_max\n");
sys_gui("set var_comment_bfs_min [concat comment_bfs_min_$vid]\n");
sys_gui("global $var_comment_bfs_min\n");
sys_gui("set var_comment_bfs_max [concat comment_bfs_max_$vid]\n");
sys_gui("global $var_comment_bfs_max\n");
sys_gui("set var_comment_del_min [concat comment_del_min_$vid]\n");
sys_gui("global $var_comment_del_min\n");
sys_gui("set var_comment_wdt_init [concat comment_wdt_init_$vid]\n");
sys_gui("global $var_comment_wdt_init\n");
sys_gui("set var_comment_hgt_init [concat comment_hgt_init_$vid]\n");
sys_gui("global $var_comment_hgt_init\n");
sys_gui("set var_comment_cal_init [concat comment_cal_init_$vid]\n");
sys_gui("global $var_comment_cal_init\n");
sys_gui("set var_comment_bfs_init [concat comment_bfs_init_$vid]\n");
sys_gui("global $var_comment_bfs_init\n");
sys_gui("set var_comment_min_rng_init [concat comment_min_rng_init_$vid]\n");
sys_gui("global $var_comment_min_rng_init\n");
sys_gui("set var_comment_max_rng_init [concat comment_max_rng_init_$vid]\n");
sys_gui("global $var_comment_max_rng_init\n");
sys_gui("set var_comment_del_init [concat comment_del_init_$vid]\n");
sys_gui("global $var_comment_del_init\n");
sys_gui("set var_comment_tlv_init [concat comment_tlv_init_$vid]\n");
sys_gui("global $var_comment_tlv_init\n");
sys_gui("set $var_comment_wdt $wdt\n");
sys_gui("set $var_comment_hgt $hgt\n");
sys_gui("set $var_comment_cal $cal\n");
sys_gui("set $var_comment_bfs $bfs\n");
sys_gui("set $var_comment_min_rng $min_rng\n");
sys_gui("set $var_comment_max_rng $max_rng\n");
sys_gui("set $var_comment_del $del\n");
sys_gui("set $var_comment_drs $drs\n");
sys_gui("set $var_comment_tmd $tmd\n");
sys_gui("set $var_comment_tlv $tlv  \n");
sys_gui("set $var_comment_bcol $bcol\n");
sys_gui("set $var_comment_gcol $gcol\n");
sys_gui("set $var_comment_fcol $fcol\n");
sys_gui("set $var_comment_f2_g1_b0 0\n");
sys_gui("set $var_comment_wdt_init $wdt\n");
sys_gui("set $var_comment_hgt_init $hgt\n");
sys_gui("set $var_comment_cal_init $cal\n");
sys_gui("set $var_comment_bfs_init $bfs\n");
sys_gui("set $var_comment_min_rng_init $min_rng\n");
sys_gui("set $var_comment_max_rng_init $max_rng\n");
sys_gui("set $var_comment_del_init $del\n");
sys_gui("set $var_comment_tlv_init $tlv \n");
sys_gui("set $var_comment_wdt_min $wdt_min\n");
sys_gui("set $var_comment_hgt_min $hgt_min\n");
sys_gui("set $var_comment_cal_min $cal_min\n");
sys_gui("set $var_comment_cal_max $cal_max\n");
sys_gui("set $var_comment_bfs_min $bfs_min\n");
sys_gui("set $var_comment_bfs_max $bfs_max\n");
sys_gui("set $var_comment_del_min $del_min\n");
sys_gui("set wdt_label [_ \"Width:\"]\n");
sys_gui("set hgt_label [_ \"Height:\"]\n");
sys_gui("set buf_header [_ \"Buffer Settings:\"]\n");
sys_gui("set cal_label [_ \"Samples Per Point:\"]\n");
sys_gui("set bfs_label [_ \"Buffer Size:\"]\n");
sys_gui("set rng_header [_ \"Signal Range:\"]\n");
sys_gui("set min_rng_label [_ \"Minval:\"]\n");
sys_gui("set max_rng_label [_ \"Maxval:\"]\n");
sys_gui("set del_header [_ \"Delay:\"]\n");
sys_gui("set del_label [_ \"Delay:\"]\n");
sys_gui("set drs_label [_ \"Alternate Drawstyle:\"]\n");
sys_gui("set tmd_label [_ \"Trigger Mode:\"]\n");
sys_gui("set tmd0_label [_ \"None\"]\n");
sys_gui("set tmd1_label [_ \"Up\"]\n");
sys_gui("set tmd2_label [_ \"Down\"]\n");
sys_gui("set tlv_label [_ \"Trigger Level:\"]\n");
sys_gui("set $var_comment_tmd0 $tmd0_label\n");
sys_gui("set $var_comment_tmd1 $tmd1_label\n");
sys_gui("set $var_comment_tmd2 $tmd2_label\n");
sys_gui("toplevel $mytoplevel -class DialogWindow\n");
sys_gui("wm title $mytoplevel [format [_ \"comment~ Properties\"] ]\n");
sys_gui("wm group $mytoplevel .\n");
sys_gui("wm resizable $mytoplevel 0 0\n");
sys_gui("wm transient $mytoplevel $::focused_window\n");
sys_gui("$mytoplevel configure -menu $::dialog_menubar\n");
sys_gui("$mytoplevel configure -padx 0 -pady 0\n");
sys_gui("::pd_bindings::dialog_bindings $mytoplevel \"comment\"\n");
// dimensions
sys_gui("labelframe $mytoplevel.dim -borderwidth 1 -pady 8 -text [_ \"Dimensions:\"]\n");
sys_gui("pack $mytoplevel.dim -side top -fill x -pady 5\n");
sys_gui("frame $mytoplevel.dim.fr\n");
sys_gui("label $mytoplevel.dim.fr.w_lab -text [_ $wdt_label]\n");
sys_gui("entry $mytoplevel.dim.fr.w_ent -textvariable $var_comment_wdt -width 4\n");
sys_gui("label $mytoplevel.dim.fr.dummy1 -text \"\" -width 1\n");
sys_gui("label $mytoplevel.dim.fr.h_lab -text [_ $hgt_label]\n");
sys_gui("entry $mytoplevel.dim.fr.h_ent -textvariable $var_comment_hgt -width 4\n");
sys_gui("pack $mytoplevel.dim.fr -side left -expand 1\n");
sys_gui("pack $mytoplevel.dim.fr.w_lab $mytoplevel.dim.fr.w_ent \\\n");
sys_gui("$mytoplevel.dim.fr.dummy1 $mytoplevel.dim.fr.h_lab $mytoplevel.dim.fr.h_ent -side left\n");
// calccount & bufsize
sys_gui("labelframe $mytoplevel.buf -borderwidth 1 -pady 8 -text [_ $buf_header]\n");
sys_gui("pack $mytoplevel.buf -side top -fill x -pady 5\n");
sys_gui("frame $mytoplevel.buf.fr\n");
sys_gui("label $mytoplevel.buf.fr.cal_lab -text [_ $cal_label]\n");
sys_gui("entry $mytoplevel.buf.fr.cal_ent -textvariable $var_comment_cal -width 4\n");
sys_gui("label $mytoplevel.buf.fr.dummy1 -text \"\" -width 1\n");
sys_gui("label $mytoplevel.buf.fr.bfs_lab -text [_ $bfs_label]\n");
sys_gui("entry $mytoplevel.buf.fr.bfs_ent -textvariable $var_comment_bfs -width 4\n");
sys_gui("pack $mytoplevel.buf.fr -side left -expand 1\n");
sys_gui("pack $mytoplevel.buf.fr.cal_lab $mytoplevel.buf.fr.cal_ent -side left\n");
sys_gui("pack $mytoplevel.buf.fr.dummy1 $mytoplevel.buf.fr.bfs_lab $mytoplevel.buf.fr.bfs_ent -side left\n");
// range
sys_gui("labelframe $mytoplevel.rng -borderwidth 1 -pady 8 -text [_ $rng_header]\n");
sys_gui("pack $mytoplevel.rng -side top -fill x -pady 5\n");
sys_gui("frame $mytoplevel.rng.fr\n");
sys_gui("label $mytoplevel.rng.fr.min_lab -text [_ $min_rng_label]\n");
sys_gui("entry $mytoplevel.rng.fr.min_ent -textvariable $var_comment_min_rng -width 8\n");
sys_gui("label $mytoplevel.rng.fr.dummy1 -text \"\" -width 1\n");
sys_gui("label $mytoplevel.rng.fr.max_lab -text [_ $max_rng_label]\n");
sys_gui("entry $mytoplevel.rng.fr.max_ent -textvariable $var_comment_max_rng -width 8\n");
sys_gui("pack $mytoplevel.rng.fr -side left -expand 1\n");
sys_gui("pack $mytoplevel.rng.fr.min_lab $mytoplevel.rng.fr.min_ent -side left\n");
sys_gui("pack $mytoplevel.rng.fr.dummy1 $mytoplevel.rng.fr.max_lab $mytoplevel.rng.fr.max_ent -side left\n");
//trigger
sys_gui("set current_tmd \"None\"\n");
sys_gui("if {[eval concat $$var_comment_tmd] == 1} \\\n");
sys_gui("{ set current_tmd \"Up\" }\n");
sys_gui("if {[eval concat $$var_comment_tmd] == 2} \\\n");
sys_gui("{ set current_tmd \"Down\" }\n");
sys_gui("labelframe $mytoplevel.trg \n");
sys_gui("pack $mytoplevel.trg -side top -fill x -pady 5\n");
sys_gui("frame $mytoplevel.trg.tmd\n");
sys_gui("label $mytoplevel.trg.tmd.lab -text [_ $tmd_label]\n");
sys_gui("button $mytoplevel.trg.tmd.trb -text $current_tmd -width 4\n");
sys_gui("label $mytoplevel.trg.dummy1 -text \"\" -width 1\n");
sys_gui("label $mytoplevel.trg.tlv_lab -text [_ $tlv_label]\n");
sys_gui("entry $mytoplevel.trg.tlv_ent -textvariable $var_comment_tlv -width 8\n");
sys_gui("$mytoplevel.trg config -borderwidth 1 -padx 5 -pady 5 -text [_ \"Trigger Settings:\"]\n");
sys_gui("pack $mytoplevel.trg.tmd\n");
sys_gui("pack $mytoplevel.trg.tmd.lab -side left\n");
sys_gui("pack $mytoplevel.trg.tmd.trb -side left\n");
sys_gui("$mytoplevel.trg config -padx 10\n");
sys_gui("pack configure $mytoplevel.trg.tmd -side left\n");
sys_gui("pack $mytoplevel.trg.dummy1 $mytoplevel.trg.tlv_lab $mytoplevel.trg.tlv_ent -side left\n");
sys_gui("menu $mytoplevel.tmd_popup\n");
sys_gui("$mytoplevel.tmd_popup add command \\\n");
sys_gui("-label \"None\" -command \"::dialog_comment::comment_trigger_mode $mytoplevel 0\"\n");
sys_gui("$mytoplevel.tmd_popup add command \\\n");
sys_gui("-label \"Up\" -command \"::dialog_comment::comment_trigger_mode $mytoplevel 1\"\n");
sys_gui("$mytoplevel.tmd_popup add command \\\n");
sys_gui("-label \"Down\" -command \"::dialog_comment::comment_trigger_mode $mytoplevel 2\"\n");
sys_gui("bind $mytoplevel.trg.tmd.trb <Button> [list tk_popup $mytoplevel.tmd_popup %X %Y]\n");
//delay & drawstyle
sys_gui("labelframe $mytoplevel.misc -borderwidth 1 -pady 8\n");
sys_gui("pack $mytoplevel.misc -side top -pady 5 -fill x\n");
sys_gui("frame $mytoplevel.misc.fr\n");
sys_gui("label $mytoplevel.misc.fr.del_lab -text [_ $del_label]\n");
sys_gui("entry $mytoplevel.misc.fr.del_ent -textvariable $var_comment_del -width 7\n");
sys_gui("label $mytoplevel.misc.fr.dummy1 -text \"\" -width 4\n");
sys_gui("label $mytoplevel.misc.fr.drs_lab -text [_ $drs_label]\n");
sys_gui("checkbutton $mytoplevel.misc.fr.drs_chk -variable $var_comment_drs \\\n");
sys_gui("-command \"::dialog_comment::apply_and_rebind_return $mytoplevel\" \n");
sys_gui("pack $mytoplevel.misc.fr -side left -expand 1\n");
sys_gui("pack $mytoplevel.misc.fr.del_lab $mytoplevel.misc.fr.del_ent \\\n");
sys_gui("$mytoplevel.misc.fr.dummy1 $mytoplevel.misc.fr.drs_lab $mytoplevel.misc.fr.drs_chk -side left\n");
// colors
sys_gui("labelframe $mytoplevel.colors -borderwidth 1 -text [_ \"Colors:\"] -padx 5 -pady 5\n");
sys_gui("pack $mytoplevel.colors -fill x\n");
sys_gui("frame $mytoplevel.colors.commentvis \n");
sys_gui("pack $mytoplevel.colors.commentvis -side top -pady 10\n");
sys_gui("canvas $mytoplevel.colors.commentvis.cv -width 81 -height 65 \\\n");
sys_gui("-relief flat -highlightthickness 0\n");
sys_gui("pack $mytoplevel.colors.commentvis.cv -in $mytoplevel.colors.commentvis\n");
sys_gui("$mytoplevel.colors.commentvis.cv create rectangle 0 0 80 64 \\\n");
sys_gui("-fill [eval concat $$var_comment_bcol] -tags {\"bg\"}\n");
sys_gui("foreach i {0 10 20 30 40 50 60 70 80} {\n");
sys_gui("$mytoplevel.colors.commentvis.cv create line $i 0 $i 64 -fill [eval concat $$var_comment_gcol] \\\n");
sys_gui("-width 0.5 -tags {\"gr\"}\n");
sys_gui("}\n");
sys_gui("foreach i {0 16 32 48 64} {\n");
sys_gui("$mytoplevel.colors.commentvis.cv create line 0 $i 80 $i -fill [eval concat $$var_comment_gcol] \\\n");
sys_gui("-width 0.5 -tags {\"gr\"}\n");
sys_gui("}\n");
sys_gui("$mytoplevel.colors.commentvis.cv create line \\\n");
sys_gui("0 32 5 19.754 10 9.367 15 2.436 \\\n");
sys_gui("20 0 25 2.436 30 9.367 35 19.754 \\\n");
sys_gui("40 32 45 44.246 50 54.624 55 61.564 \\\n");
sys_gui("60 64 65 61.564 70 54.624 75 44.246 \\\n");
sys_gui("80 32 \\\n");
sys_gui("-smooth bezier -fill [eval concat $$var_comment_fcol] \\\n");
sys_gui("-width 0.9 -tags {\"fg\"}\n");
sys_gui("frame $mytoplevel.colors.dummy\n");
sys_gui("pack $mytoplevel.colors.dummy -side top -pady 10\n");
sys_gui("frame $mytoplevel.colors.select\n");
sys_gui("pack $mytoplevel.colors.select -side top\n");
sys_gui("radiobutton $mytoplevel.colors.select.radio0 -value 0 -variable \\\n");
sys_gui("$var_comment_f2_g1_b0 -text [_ \"Background\"] -justify left\n");
sys_gui("radiobutton $mytoplevel.colors.select.radio1 -value 1 -variable \\\n");
sys_gui("$var_comment_f2_g1_b0 -text [_ \"Grid\"] -justify left\n");
sys_gui("radiobutton $mytoplevel.colors.select.radio2 -value 2 -variable \\\n");
sys_gui("$var_comment_f2_g1_b0 -text [_ \"Phosphor\"] -justify left\n");
sys_gui("pack $mytoplevel.colors.select.radio0 $mytoplevel.colors.select.radio1 \\\n");
sys_gui("$mytoplevel.colors.select.radio2 -side left\n");
sys_gui("frame $mytoplevel.colors.sections \n");
sys_gui("pack $mytoplevel.colors.sections -side top -pady 5\n");
sys_gui("button $mytoplevel.colors.sections.but -text [_ \"Compose color\"] \\\n");
sys_gui("-command \"::dialog_comment::comment_choose_col_bkgrfg $mytoplevel\"\n");
sys_gui("pack $mytoplevel.colors.sections.but -side left -anchor w -pady 5 \\\n");
sys_gui("-expand yes -fill x\n");
// color scheme by Mary Ann Benedetto http://piR2.org
sys_gui("foreach r {r1 r2 r3} hexcols {\n");
sys_gui("{ \"#FFFFFF\" \"#DFDFDF\" \"#BBBBBB\" \"#FFC7C6\" \"#FFE3C6\" \"#FEFFC6\" \"#C6FFC7\" \"#C6FEFF\" \"#C7C6FF\" \"#E3C6FF\" }\n");
sys_gui("{ \"#9F9F9F\" \"#7C7C7C\" \"#606060\" \"#FF0400\" \"#FF8300\" \"#FAFF00\" \"#00FF04\" \"#00FAFF\" \"#0400FF\" \"#9C00FF\" }\n");
sys_gui("{ \"#404040\" \"#202020\" \"#000000\" \"#551312\" \"#553512\" \"#535512\" \"#0F4710\" \"#0E4345\" \"#131255\" \"#2F004D\" } } \\\n");
sys_gui("{\n");
sys_gui("frame $mytoplevel.colors.$r\n");
sys_gui("pack $mytoplevel.colors.$r -side top\n");
sys_gui("foreach i { 0 1 2 3 4 5 6 7 8 9} hexcol $hexcols \\\n");
sys_gui("{\n");
sys_gui("label $mytoplevel.colors.$r.c$i -background $hexcol -activebackground $hexcol -relief ridge -padx 7 -pady 0\n");
sys_gui("bind $mytoplevel.colors.$r.c$i <Button> \"::dialog_comment::comment_preset_col $mytoplevel $hexcol\"\n");
sys_gui("}\n");
sys_gui("pack $mytoplevel.colors.$r.c0 $mytoplevel.colors.$r.c1 $mytoplevel.colors.$r.c2 $mytoplevel.colors.$r.c3 \\\n");
sys_gui("$mytoplevel.colors.$r.c4 $mytoplevel.colors.$r.c5 $mytoplevel.colors.$r.c6 $mytoplevel.colors.$r.c7 \\\n");
sys_gui("$mytoplevel.colors.$r.c8 $mytoplevel.colors.$r.c9 -side left\n");
sys_gui("}\n");
//buttons
sys_gui("frame $mytoplevel.cao -pady 10\n");
sys_gui("pack $mytoplevel.cao -side top -expand 1 -fill x\n");
sys_gui("button $mytoplevel.cao.cancel -text [_ \"Cancel\"] \\\n");
sys_gui("-command \"::dialog_comment::cancel $mytoplevel\"\n");
sys_gui("pack $mytoplevel.cao.cancel -side left -padx 10 -expand 1 -fill x\n");
sys_gui("if {$::windowingsystem ne \"aqua\"} {\n");
sys_gui("button $mytoplevel.cao.apply -text [_ \"Apply\"] \\\n");
sys_gui("-command \"::dialog_comment::apply $mytoplevel\"\n");
sys_gui("pack $mytoplevel.cao.apply -side left -padx 10 -expand 1 -fill x\n");
sys_gui("}\n");
sys_gui("button $mytoplevel.cao.ok -text [_ \"OK\"] \\\n");
sys_gui("-command \"::dialog_comment::ok $mytoplevel\" -default active\n");
sys_gui("pack $mytoplevel.cao.ok -side left -padx 10 -expand 1 -fill x\n");
sys_gui("$mytoplevel.dim.fr.w_ent select from 0\n");
sys_gui("$mytoplevel.dim.fr.w_ent select adjust end\n");
sys_gui("focus $mytoplevel.dim.fr.w_ent\n");
// live widget updates on OSX in lieu of Apply button
sys_gui("if {$::windowingsystem eq \"aqua\"} {\n");
// call apply on Return in entry boxes that are in focus & rebind Return to ok button
sys_gui("bind $mytoplevel.dim.fr.w_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.dim.fr.h_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.buf.fr.cal_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.buf.fr.bfs_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.rng.fr.min_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.rng.fr.max_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.trg.tlv_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
sys_gui("bind $mytoplevel.misc.fr.del_ent <KeyPress-Return> \"::dialog_comment::apply_and_rebind_return $mytoplevel\"\n");
// unbind Return from ok button when an entry takes focus
sys_gui("$mytoplevel.dim.fr.w_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.dim.fr.h_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.buf.fr.cal_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.buf.fr.bfs_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.rng.fr.min_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.rng.fr.max_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.trg.tlv_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
sys_gui("$mytoplevel.misc.fr.del_ent config -validate focusin -vcmd \"::dialog_comment::unbind_return $mytoplevel\"\n");
// remove cancel button from focus list since it's not activated on Return
sys_gui("$mytoplevel.cao.cancel config -takefocus 0\n");
// can't see focus for buttons, so disable it
sys_gui("$mytoplevel.trg.tmd.trb config -takefocus 0\n");
sys_gui("$mytoplevel.colors.select.radio0 config -takefocus 0\n");
sys_gui("$mytoplevel.colors.select.radio1 config -takefocus 0\n");
sys_gui("$mytoplevel.colors.select.radio2 config -takefocus 0\n");
sys_gui("$mytoplevel.colors.sections.but config -takefocus 0\n");
// show active focus on the ok button as it *is* activated on Return
sys_gui("$mytoplevel.cao.ok config -default normal\n");
sys_gui("bind $mytoplevel.cao.ok <FocusIn> \"$mytoplevel.cao.ok config -default active\"\n");
sys_gui("bind $mytoplevel.cao.ok <FocusOut> \"$mytoplevel.cao.ok config -default normal\"\n");
sys_gui("}\n");
sys_gui("}\n");
// for live widget updates on OSX
sys_gui("proc ::dialog_comment::apply_and_rebind_return {mytoplevel} {\n");
sys_gui("::dialog_comment::apply $mytoplevel\n");
sys_gui("bind $mytoplevel <KeyPress-Return> \"::dialog_comment::ok $mytoplevel\"\n");
sys_gui("focus $mytoplevel.cao.ok\n");
sys_gui("return 0\n");
sys_gui("}\n");
// for live widget updates on OSX
sys_gui("proc ::dialog_comment::unbind_return {mytoplevel} {\n");
sys_gui("bind $mytoplevel <KeyPress-Return> break\n");
sys_gui("return 1\n");
sys_gui("}\n");
