# this conditional will make sense LATER, when TCL_LIB is ./configured
ifdef TCL_LIB
TYPES = TOT TOW WIDGET PLUSTOT
else
TYPES = TOT TOW WIDGET
endif

TOT_SOURCES = tot.c
TOW_SOURCES = tow.c
WIDGET_SOURCES = widget.c
PLUSTOT_SOURCES = plustot.c
